DROP TABLE COVID_TS_CONFIRMED;

  CREATE TABLE COVID19_TS_CONFIRMED
   (
   PROVINCE_STATE   VARCHAR2(250),
   COUNTRY_REGION   VARCHAR2(250),
   LATTITUDE        VARCHAR2(250),
   LONGITUDE        VARCHAR2(250),
   UPDATED_DATE     VARCHAR2(250),
   DATA_VALUE       VARCHAR2(250)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "DATA_LOAD_DIR"
      ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE
        FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' 
        MISSING FIELD VALUES ARE NULL
                   )
      LOCATION
       ( "DATA_LOAD_DIR":'time_series-ncov-Confirmed.csv'
       )
    )
   REJECT LIMIT UNLIMITED ;
   
  CREATE TABLE COVID19_TS_DEATHS
   (
   PROVINCE_STATE   VARCHAR2(250),
   COUNTRY_REGION   VARCHAR2(250),
   LATTITUDE        VARCHAR2(250),
   LONGITUDE        VARCHAR2(250),
   UPDATED_DATE     VARCHAR2(250),
   DATA_VALUE       VARCHAR2(250)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "DATA_LOAD_DIR"
      ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE
        FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' 
        MISSING FIELD VALUES ARE NULL
                   )
      LOCATION
       ( "DATA_LOAD_DIR":'time_series-ncov-Deaths.csv'
       )
    )
   REJECT LIMIT UNLIMITED ;

  CREATE TABLE COVID19_TS_RECOVERED
   (
   PROVINCE_STATE   VARCHAR2(250),
   COUNTRY_REGION   VARCHAR2(250),
   LATTITUDE        VARCHAR2(250),
   LONGITUDE        VARCHAR2(250),
   UPDATED_DATE     VARCHAR2(250),
   DATA_VALUE       VARCHAR2(250)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "DATA_LOAD_DIR"
      ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE
        FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' 
        MISSING FIELD VALUES ARE NULL
                   )
      LOCATION
       ( "DATA_LOAD_DIR":'time_series-ncov-Recovered.csv'
       )
    )
   REJECT LIMIT UNLIMITED ;   

  CREATE TABLE SYNH_LOCATIONS
   (
   PROVINCE_STATE   VARCHAR2(250),
   COUNTRY_REGION   VARCHAR2(250),
   WORLD_REGION     VARCHAR2(250),
   ALT_PROVINCE     VARCHAR2(250)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "DATA_LOAD_DIR"
      ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE
        FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' 
        MISSING FIELD VALUES ARE NULL
                   )
      LOCATION
       ( "DATA_LOAD_DIR":'synh_locations.csv'
       )
    )
   REJECT LIMIT UNLIMITED ;   

CREATE TABLE SYNH_COVID19 (
    PROVINCE_STATE      VARCHAR2(250),
    COUNTRY_REGION      VARCHAR2(250),
    LATTITUDE           VARCHAR2(250),
    LONGITUDE           VARCHAR2(250),
    CONFIRMED           NUMBER,
    DEATHS              NUMBER,
    RECOVERED           NUMBER,
    LAST_UPDATED_DT     DATE,
    UPDATED_TS          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


BUENOS AIRES	
Argentina




Argentina